language: go
sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=d7dd95e600e1e6d6459116df4fe6e4354465d857d4bd133c96ea10b0da03ee5a

go:
  - "1.2"
  - "1.3"
  - "1.4"
  - "1.5"
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: go test -v -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
