language: go
sudo: false

notifications:
  email: false

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"

install:
  - go get -t -v ./...

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get golang.org/x/lint/golint                             # Install golint
  - go get honnef.co/go/tools/cmd/megacheck                     # Install megacheck
  - go get github.com/fzipp/gocyclo                             # Install gocycle

  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter # Install CodeClimate reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - test -z $(gofmt -s -l $GO_FILES)           # Fail if a .go file hasn't been formatted with gofmt
  - go vet ./...                               # go vet is the official Go static analyzer
  - megacheck ./...                            # "go vet on steroids" + linter
  - gocyclo -over 19 $GO_FILES                 # forbid code with huge functions
  - golint -set_exit_status $(go list ./...)   # one last linter
  - go test -v -race -coverprofile c.out ./... # Run the tests with race-condition enabled and generate the coverage report

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT # Report coverage to CodeClimate